/** Shared data shapes for the Agéntdex (generated by tools/build_dex.py). */

import { t } from '../i18n.ts';

export type TypeKey =
  | 'volt' | 'alloy' | 'data' | 'thermal' | 'cryo'
  | 'servo' | 'optic' | 'neural' | 'viral' | 'quantum';

export interface TypeDef {
  key: TypeKey;
  name: string;
  color: string;
  dark: string;
}

export type MoveCategory = 'physical' | 'special' | 'status';

export interface MoveDef {
  key: string;
  name: string;
  type: TypeKey;
  category: MoveCategory;
  power: number;
  accuracy: number;
  pp: number;
  priority: number;
  effect: string | null;
  effectChance: number;
  target: 'foe' | 'self' | 'all';
  desc: string;
}

export interface Stats {
  hp: number;
  atk: number;
  def: number;
  spa: number;
  spd: number;
  spe: number;
}

export type GrowthRate = 'fast' | 'medium_fast' | 'medium_slow' | 'slow';

/**
 * An alternate appearance of a species.
 *
 * `colour` forms are pure palette swaps - same typing, same learnset, so they
 * exist only to make a wild encounter feel personal. `shape` forms are proper
 * variants: they keep the base stats but bring their own second type and their
 * own signature moves. Both resolve to their own sprite, `<species>_<form>`.
 */
export type FormKind = 'colour' | 'shape';

export interface FormDef {
  key: string;
  label: string;
  kind: FormKind;
  /** Colour forms: the shell tint, for UI chips. Null on the base appearance. */
  tint?: string | null;
  types?: TypeKey[];
  learnset?: [number, string][];
}

export interface SpeciesDef {
  id: number;
  key: string;
  name: string;
  types: TypeKey[];
  genus: string;
  baseStats: Stats;
  catchRate: number;
  baseExp: number;
  growthRate: GrowthRate;
  height: number;
  weight: number;
  dexEntry: string;
  art: string;
  learnset: [number, string][];
  evolution: { to: string; level: number } | null;
  airborne: boolean;
  cell: { w: number; h: number };
  legendary: boolean;
  forms: FormDef[];
  /** Real hardware this design pays homage to. Credit, never shown as a name. */
  inspired: string;
}

export interface Dex {
  version: number;
  types: Record<TypeKey, TypeDef>;
  typeChart: Record<TypeKey, Partial<Record<TypeKey, number>>>;
  moves: Record<string, MoveDef>;
  species: Record<string, SpeciesDef>;
}

/** Raw shape emitted by tools/build_dex.py (arrays keyed by `key`). */
interface RawDex {
  version: number;
  types: TypeDef[];
  typeChart: Record<string, Record<string, number>>;
  moves: MoveDef[];
  species: SpeciesDef[];
}

function byKey<T extends { key: string }>(list: T[]): Record<string, T> {
  const out: Record<string, T> = {};
  for (const entry of list) out[entry.key] = entry;
  return out;
}

let dex: Dex | null = null;

export function setDex(raw: RawDex | Dex): void {
  if (Array.isArray((raw as RawDex).species)) {
    const r = raw as RawDex;
    dex = {
      version: r.version,
      types: byKey(r.types) as Record<TypeKey, TypeDef>,
      typeChart: r.typeChart as Dex['typeChart'],
      moves: byKey(r.moves),
      species: byKey(r.species),
    };
  } else {
    dex = raw as Dex;
  }
}

export function DEX(): Dex {
  if (!dex) throw new Error('Agentdex not loaded');
  return dex;
}

export function species(key: string): SpeciesDef {
  const s = DEX().species[key];
  if (!s) throw new Error(`Unknown species: ${key}`);
  return s;
}

export function speciesById(id: number): SpeciesDef | undefined {
  return Object.values(DEX().species).find((s) => s.id === id);
}

export function move(key: string): MoveDef {
  const m = DEX().moves[key];
  if (!m) throw new Error(`Unknown move: ${key}`);
  return m;
}

export function typeDef(key: TypeKey): TypeDef {
  return DEX().types[key];
}

export function allSpecies(): SpeciesDef[] {
  return Object.values(DEX().species).sort((a, b) => a.id - b.id);
}

// --------------------------------------------------------------------------- //
// Forms
// --------------------------------------------------------------------------- //
export function formsOf(sp: SpeciesDef | string): FormDef[] {
  return (typeof sp === 'string' ? species(sp) : sp).forms ?? [];
}

export function formOf(sp: SpeciesDef | string, form: string | null | undefined): FormDef | null {
  if (!form) return null;
  return formsOf(sp).find((f) => f.key === form) ?? null;
}

/** Typing after the form override, which only `shape` forms carry. */
export function typesOf(speciesKey: string, form?: string | null): TypeKey[] {
  const sp = species(speciesKey);
  return formOf(sp, form)?.types ?? sp.types;
}

export function learnsetOf(speciesKey: string, form?: string | null): [number, string][] {
  const sp = species(speciesKey);
  return formOf(sp, form)?.learnset ?? sp.learnset;
}

/**
 * Asset key for a species/form pair. Forms whose art is the untouched base
 * generation (SNOW) ship no sheet of their own, so they fall back to the
 * species key rather than 404ing.
 */
export function spriteKey(speciesKey: string, form?: string | null): string {
  const f = formOf(speciesKey, form);
  if (!f) return speciesKey;
  if (f.kind === 'colour' && !f.tint) return speciesKey;
  return `${speciesKey}_${f.key}`;
}

/**
 * Whether a `<key>_cover` sheet was shipped. Data-driven off the learnset so a
 * new shell-hider only has to learn COVER to get its pose queued.
 */
export function hasCoverPose(speciesKey: string, form?: string | null): boolean {
  return learnsetOf(speciesKey, form).some(([, key]) => key === 'cover');
}

export function dexSize(): number {
  return Object.keys(DEX().species).length;
}

// --------------------------------------------------------------------------- //
// Localised text
// --------------------------------------------------------------------------- //
/**
 * The dex JSON stays English; it is the single source of truth that the art
 * pipeline and the tests read. Anything the player can actually see goes
 * through these accessors so it picks up the active language, while species
 * names deliberately do not: an AGÉNTMON is called the same thing worldwide.
 */
export function moveName(m: MoveDef | string): string {
  return t(typeof m === 'string' ? move(m).name : m.name);
}

export function moveDesc(m: MoveDef | string): string {
  return t(typeof m === 'string' ? move(m).desc : m.desc);
}

export function genusOf(s: SpeciesDef | string): string {
  return t(typeof s === 'string' ? species(s).genus : s.genus);
}

export function dexEntryOf(s: SpeciesDef | string): string {
  return t(typeof s === 'string' ? species(s).dexEntry : s.dexEntry);
}

export function typeName(key: TypeKey): string {
  return t(typeDef(key).name);
}

/**
 * Form labels are descriptors (SKY, ZEBRA, HALLOW), not names, so unlike a
 * species name they DO translate.
 */
export function formLabel(f: FormDef | null): string {
  return f ? t(f.label) : '';
}

/** Every localisable dex string (never species names), for the extractor. */
export function dexStrings(): string[] {
  const d = DEX();
  const out: string[] = [];
  for (const s of Object.values(d.species)) {
    out.push(s.genus, s.dexEntry);
    for (const f of s.forms ?? []) out.push(f.label);
  }
  for (const m of Object.values(d.moves)) out.push(m.name, m.desc);
  for (const ty of Object.values(d.types)) out.push(ty.name);
  return out;
}

/** Damage multiplier of `atk` type against a defender's type list. */
export function typeEffect(atk: TypeKey, defTypes: TypeKey[]): number {
  const row = DEX().typeChart[atk] ?? {};
  let mult = 1;
  for (const t of defTypes) mult *= row[t] ?? 1;
  return mult;
}

// --------------------------------------------------------------------------- //
// Experience curves
// --------------------------------------------------------------------------- //
export function expForLevel(rate: GrowthRate, level: number): number {
  const n = Math.max(1, level);
  switch (rate) {
    case 'fast': return Math.floor((4 * n ** 3) / 5);
    case 'slow': return Math.floor((5 * n ** 3) / 4);
    case 'medium_slow':
      return Math.max(0, Math.floor((6 / 5) * n ** 3 - 15 * n ** 2 + 100 * n - 140));
    case 'medium_fast':
    default:
      return n ** 3;
  }
}

export function levelForExp(rate: GrowthRate, exp: number): number {
  let lv = 1;
  while (lv < 100 && expForLevel(rate, lv + 1) <= exp) lv++;
  return lv;
}
